### ISSUE TITLE
Can you package this up in a .Net core docker container?

### ISSUE THREAD

**Issue by emilebosch** [kudchikarsk/webapi-generator#2]
Allows us linux/osx users to use it just like that!

**Comment by kudchikarsk** [comment]
Sure thing but that would be pretty simple once .NET version is complete!

**Comment by emilebosch** [comment]
What do you mean?

**Comment by kudchikarsk** [comment]
My focus is on .NET MVC 5 WebApi, for now, I will complete this along with angular frontend generators then will turn to .NET core generator. Does this answer your consent?
